version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/api"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/scraper"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/scraper"
    schedule:
      interval: "daily"
